# Introduction to PyTorch
## Tensors
Let's get started with the basics. Tensors are similar to numpy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [2]:
from __future__ import print_function
import torch

We'll start by randomly initializing a matrix.  

In [3]:
x = torch.rand(3,5)
print(x)


 0.8504  0.9059  0.0569  0.3210  0.7888
 0.9745  0.6749  0.4882  0.2655  0.9318
 0.2443  0.6664  0.4422  0.1117  0.4756
[torch.FloatTensor of size 3x5]



We can get the size of tensors by calling `torch.size`.

In [10]:
print(x.size())

torch.Size([3, 5])


We can also reshape tensors using the `.view` function. Using a `-1` in one of the dimensions indicates that that dimension's size should be infered.

In [9]:
print(x.view(-1, 3))


 0.8504  0.9059  0.0569
 0.3210  0.7888  0.9745
 0.6749  0.4882  0.2655
 0.9318  0.2443  0.6664
 0.4422  0.1117  0.4756
[torch.FloatTensor of size 5x3]



There are multiple different syntaxes for operations:

In [4]:
y = torch.rand(3, 5)
print('Y:', y)

result1 = y + x              # numpy form
result2 = torch.add(x, y)    # torch form
y.add_(x)                    # in-place
print('Result 1:', result1, 'Result 2:', result2, 'Result 3:', y)

Y: 
 0.5838  0.2211  0.9111  0.6426  0.8530
 0.0087  0.7193  0.5980  0.7738  0.9423
 0.0134  0.2410  0.5535  0.3047  0.5093
[torch.FloatTensor of size 3x5]

Result 1: 
 0.6334  0.5534  1.7858  1.6258  1.3061
 0.8190  1.2543  0.6328  1.0239  1.8263
 0.5013  0.8701  1.0894  0.4676  0.8408
[torch.FloatTensor of size 3x5]
 Result 2: 
 0.6334  0.5534  1.7858  1.6258  1.3061
 0.8190  1.2543  0.6328  1.0239  1.8263
 0.5013  0.8701  1.0894  0.4676  0.8408
[torch.FloatTensor of size 3x5]
 Result 3: 
 0.6334  0.5534  1.7858  1.6258  1.3061
 0.8190  1.2543  0.6328  1.0239  1.8263
 0.5013  0.8701  1.0894  0.4676  0.8408
[torch.FloatTensor of size 3x5]



PyTorch supports numpy-like indexing:

In [5]:
print(y[:, :2])  # Retrieve only the first two columns


 0.6334  0.5534
 0.8190  1.2543
 0.5013  0.8701
[torch.FloatTensor of size 3x2]



## Converting Between torch Tensor and numpy Array  
PyTorch makes it very easy to switch between torch tensors and numpy arrays:  
Convert a torch tensor to numpy with `.numpy()`.  
Convert a numpy array to a torch tensor with `torch.from_numpy()`.

In [6]:
x = x.numpy()
print(x, type(x))

x = torch.from_numpy(x)
print(x, type(x))

[[ 0.04952376  0.33224967  0.87471962  0.98314464  0.45310757]
 [ 0.81023103  0.53497314  0.03485238  0.25011182  0.88396251]
 [ 0.48792541  0.62901938  0.53591692  0.16294441  0.33149886]] <type 'numpy.ndarray'>

 0.0495  0.3322  0.8747  0.9831  0.4531
 0.8102  0.5350  0.0349  0.2501  0.8840
 0.4879  0.6290  0.5359  0.1629  0.3315
[torch.FloatTensor of size 3x5]
 <class 'torch.FloatTensor'>


## CUDA Tensors  
Tensors can be moved onto the GPU using the `.cuda` function, and back on to the cpu using `.cpu`. You can also control which GPU the tensor is placed on by passing the GPU number.

In [15]:
if torch.cuda.is_available():
    x = x.cuda(0)  # place x on GPU0
    print(type(x))
    
x = x.cpu()
print(type(x))

<class 'torch.cuda.FloatTensor'>
<class 'torch.FloatTensor'>


# Autograd  
The `autograd` package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

## Variable  
The `autograd.Variable` class is wrapped around Tensors in order to record each operation performed on it. With this information the gradients can be calculated. 

In [8]:
import numpy as np
import torch
from torch.autograd import Variable

x = np.array([3])                     # numpy array
x = torch.from_numpy(x)               # torch tensor
x = Variable(x, requires_grad=True)   # torch Variable
print(x)

Variable containing:
 3
[torch.LongTensor of size 1]



## Gradients
We can calculate gradients for all previous operations with the `.backward()` function. Normally we will use this on the output of our loss function to backpropogate the error through our neural network, but for now we will use it to simply calculate the derivative of the function y = x^2 at x = 3. The derivative of x^2 is 2x, so our gradient at x = 3 should be 2 * 3 = 6.

In [9]:
y = x * x
print(y)

y.backward()
print(x.grad)

Variable containing:
 9
[torch.LongTensor of size 1]

Variable containing:
 6
[torch.LongTensor of size 1]

